---
- name: Check if Zabbix release package is installed
  ansible.builtin.stat:
    path: "/etc/apt/sources.list.d/zabbix.list"
  register: zabbix_release_installed

- name: Download Zabbix release package
  ansible.builtin.get_url:
    url: "{{ zabbix_package_url }}"
    dest: "/tmp/{{ zabbix_package_name }}"
  when: not zabbix_release_installed.stat.exists

- name: Install Zabbix release package
  ansible.builtin.apt:
    deb: "/tmp/{{ zabbix_package_name }}"
  when: not zabbix_release_installed.stat.exists

- name: Update repository cache and install Zabbix-agent2
  ansible.builtin.apt:
    update_cache: yes
    name:
      - zabbix-agent2
      - zabbix-agent2-plugin-*
    state: present

- name: Configure Zabbix Agent
  ansible.builtin.template:
    src: "templates/zabbix_agent2.conf.j2"
    dest: "/etc/zabbix/zabbix_agent2.conf"
    backup: yes

- name: Restart and enable Zabbix Agent service
  ansible.builtin.systemd:
    name: zabbix-agent2
    state: restarted
    enabled: yes
